import { http, HttpResponse, delay } from 'msw'
import { MOCK_EVIDENCE } from '../data'

const evidence = MOCK_EVIDENCE.map(e => ({ ...e }))

// Tiny mock payloads per content-type (returned by the download handler)
function mockFileContent(contentType: string, filename: string): string {
  if (contentType === 'application/json') {
    return JSON.stringify({ mock: true, filename, generated: new Date().toISOString() }, null, 2)
  }
  // Default: plain text for all types (mock layer — not real binary)
  return `# Mock evidence file: ${filename}\n# Generated by LBRO mock layer\n# Content-Type: ${contentType}\n`
}

export const evidenceHandlers = [
  // Global evidence list
  http.get('/api/v1/evidence', async ({ request }) => {
    await delay(250)
    const url = new URL(request.url)
    const incident_id = url.searchParams.get('incident_id')
    const page      = Number(url.searchParams.get('page')      ?? 1)
    const page_size = Number(url.searchParams.get('page_size') ?? 20)

    const filtered = incident_id ? evidence.filter(e => e.incident_id === incident_id) : evidence
    const total = filtered.length
    const items = filtered.slice((page - 1) * page_size, page * page_size).map(e => ({
      ...e,
      download_url: '/api/v1/evidence/' + e.id + '/download',
    }))
    return HttpResponse.json({ items, total, page, page_size })
  }),

  // Per-incident evidence list
  http.get('/api/v1/incidents/:id/evidence', async ({ params }) => {
    await delay(200)
    const items = evidence
      .filter(e => e.incident_id === params.id)
      .map(e => ({ ...e, download_url: '/api/v1/evidence/' + e.id + '/download' }))
    return HttpResponse.json(items)
  }),

  // Direct file download -- served from mock binary (mirrors PostgreSQL storage in production)
  http.get('/api/v1/evidence/:id/download', async ({ params }) => {
    await delay(300)
    const e = evidence.find(ev => ev.id === params.id)
    if (!e) return HttpResponse.json({ detail: 'Not found' }, { status: 404 })
    const body = mockFileContent(e.content_type, e.original_filename)
    return new HttpResponse(new Blob([body]), {
      status: 200,
      headers: {
        'Content-Type': e.content_type,
        'Content-Disposition': 'attachment; filename="' + e.original_filename + '"',
        'Content-Length': String(body.length),
        'X-Content-Type-Options': 'nosniff',
      },
    })
  }),

  // Legacy download-url endpoint -- now returns the direct API path
  http.get('/api/v1/evidence/:id/download-url', async ({ params }) => {
    await delay(150)
    const e = evidence.find(ev => ev.id === params.id)
    if (!e) return HttpResponse.json({ detail: 'Not found' }, { status: 404 })
    return HttpResponse.json({ url: '/api/v1/evidence/' + e.id + '/download', expires_at: null })
  }),

  // Verify integrity
  http.post('/api/v1/evidence/:id/verify', async ({ params }) => {
    await delay(300)
    const e = evidence.find(ev => ev.id === params.id)
    if (!e) return HttpResponse.json({ detail: 'Not found' }, { status: 404 })
    return HttpResponse.json({ ok: true, hash: e.sha256_hash })
  }),
]
